### PR TITLE
[+] Add overview for psyco in Guangxi

### PR DESCRIPTION
**Pull request by Twinsherry**
- Add The First Affiliated Hospital of Guangxi Medical University
- Add Nanning No.5 People's Hospital
- Delete You Meina in unconfirmed list

It should be improved then... we know. but we still want to commit this owing to scarce medical resources in Guangxi region. We add some applicable psychiatrists in this overview.

### CODE REVIEW

**Review by saeziae — APPROVED** [review]

**Comment by Twinsherry** [comment]
The truth of diagnosis certificate has been verified. 

But we're sorry for that we cannot push her certificate to MtF.wiki page.

**Comment by Twinsherry** [comment]
Record other contributors in this page: 果汁 灰雁

**Comment by Cryolitia** [comment]
请上传诊断证明的原始图片，无需自行添加水印

**Comment by Twinsherry** [comment]
> 请上传诊断证明的原始图片，无需自行添加水印

It's not my diagnosis certificate…

**Comment by Cryolitia** [comment]
> She only hope to upload that.

那就删除诊断证明图片仅保留文字部分吧

**Comment by Twinsherry** [comment]
> > She only hope to upload that.
> 
> 那就删除诊断证明图片仅保留文字部分吧

Resolved.
好的，已修改~

**Review by Cryolitia — APPROVED** [review]

**Pull request merged**
